source "https://rubygems.org"
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby "3.2.8"

#Server para ativar printar mais bonito utilizando comando ap, nao esquecer de dar o require 'ap'
gem "awesome_print"

#Serve para os configurar logins e sessões do projeto
#gem "devise"

# Bundle edge Rails instead: gem "rails", github: "rails/rails", branch: "main"
gem "rails", "~> 7.1"

# The original asset pipeline for Rails [https://github.com/rails/sprockets-rails]
gem "sprockets-rails"

# Use postgresql as the database for Active Record
gem "pg", "~> 1.1"

# Use the Puma web server [https://github.com/puma/puma]
gem "puma", ">= 6.0.0"

#Gem usada para criar paginação e gem para a tradução da gem
#gem 'kaminari'
#gem 'kaminari-i18n'

#gem 'cpf_cnpj'
# Use JavaScript with ESM import maps [https://github.com/rails/importmap-rails]
#gem "importmap-rails"

# Hotwire's SPA-like page accelerator [https://turbo.hotwired.dev]
gem "turbo-rails"

# Hotwire's modest JavaScript framework [https://stimulus.hotwired.dev]
gem "stimulus-rails"

# Build JSON APIs with ease [https://github.com/rails/jbuilder]
#gem "jbuilder"

# Use Redis adapter to run Action Cable in production
# gem "redis", "~> 4.0"
gem "redis", ">= 4.0.1"

gem "sidekiq"

# Use Kredis to get higher-level data types in Redis [https://github.com/rails/kredis]
# gem "kredis"

# Use Active Model has_secure_password [https://guides.rubyonrails.org/active_model_basics.html#securepassword]
#gem "bcrypt", "~> 3.1.7"

# Windows does not include zoneinfo files, so bundle the tzinfo-data gem
#gem "tzinfo-data", platforms: %i[ mingw mswin x64_mingw jruby ]

# Reduces boot times through caching; required in config/boot.rb
gem "bootsnap", require: false

# Use Sass to process CSS
gem "sassc-rails"
# Instalei para usar os icones no front
#gem 'font-awesome-sass'
# Usar a gem do rake
gem "rake"
# Usar a gem do bootstrap
#gem "bootstrap", "~> 4.1.3"
# Gem para menssagens do flash
#gem "bootstrap_flash_messages"
# Use Active Storage variants [https://guides.rubyonrails.org/active_storage_overview.html#transforming-images]
# gem "image_processing", "~> 1.2"
#gem "psych", "~> 5.1.2"
#recaptcha
#gem 'recaptcha', require: 'recaptcha/rails'
#gem "google-cloud-recaptcha_enterprise"
#group :development, :test do
  # See https://guides.rubyonrails.org/debugging_rails_applications.html#debugging-with-the-debug-gem
  #gem "debug", platforms: %i[ mri mingw x64_mingw ]
#end

group :development do
  # Use console on exceptions pages [https://github.com/rails/web-console]
  #gem "web-console"

  # Add speed badges [https://github.com/MiniProfiler/rack-mini-profiler]
  # gem "rack-mini-profiler"
   gem 'rack', '~> 3.1.7'

  # Speed up commands on slow machines / big apps [https://github.com/rails/spring]
  # gem "spring"
end
