FROM postgres:15

# Definindo a senha padrão do PostgreSQL (pode ser alterada via docker-compose.yml)
ENV POSTGRES_USER=postgres
ENV POSTGRES_PASSWORD=entrevista
ENV POSTGRES_DB=entrevista

# Definindo o diretório de trabalho
WORKDIR /var/lib/postgresql/data

# Expondo a porta do PostgreSQL
EXPOSE 5432


